export const PORT = Number(process.env.PORT ?? 3100);
export const DEFAULT_CURRENCY = 'USD';
export const API_AMOUNT_MULTIPLIER = 1000000;
export const BOOK_AMOUNT_MULTIPLIER = 100;
export const DISPLAYED_STARTING_BALANCE = 999999999;
export const STARTING_BALANCE = DISPLAYED_STARTING_BALANCE * API_AMOUNT_MULTIPLIER;
