export const SYMBOL_NAME = {
	HIGH_1: 'HIGH_1',
	HIGH_2: 'HIGH_2',
	HIGH_3: 'HIGH_3',
	HIGH_4: 'HIGH_4',
	LOW_1: 'LOW_1',
	LOW_2: 'LOW_2',
	LOW_3: 'LOW_3',
	LOW_4: 'LOW_4',
	VALUE_COIN: 'VALUE_COIN',
	EMPTY_COIN: 'EMPTY_COIN',
} as const;

export const REGULAR_SYMBOL_NAME_VALUES = [
	SYMBOL_NAME.HIGH_1,
	SYMBOL_NAME.HIGH_2,
	SYMBOL_NAME.HIGH_3,
	SYMBOL_NAME.HIGH_4,
	SYMBOL_NAME.LOW_1,
	SYMBOL_NAME.LOW_2,
	SYMBOL_NAME.LOW_3,
	SYMBOL_NAME.LOW_4,
] as const;

export const COIN_SYMBOL_NAME_VALUES = [SYMBOL_NAME.VALUE_COIN, SYMBOL_NAME.EMPTY_COIN] as const;
